apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/dotnet-test:6f69f4bd4b5a66a22812573746223366abb295d3@sha256:7044001721ec0582cfbf04e495a61dcf38b443b76fddc14c6957a400e3d2ee07
          name: container-image
